version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: backend-container
    # environment:
    #   - NODE_ENV=production
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
